import { FaFigma, FaReact, FaJava } from 'react-icons/fa';
import { SiWeb3Dotjs } from 'react-icons/si';

const data = [
  {
    id: 1,
    image: 'img/1.jpg',
    icon: <FaFigma />,
    title: 'Backend',
    category: 'Backend',
    tags: ['Mongo', ' Express', ' Node', ' React'],
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
    source: '#',
    visit: '#',
  },
  {
    id: 2,
    image: 'img/1.png',
    icon: <FaReact />,
    title: 'React.js',
    category: 'Frontend',
    tags: ['React.js', ' ,HTML', ' ,CSS'],
    desc: 'This project is a media company website app. It was built with React, HTML and CSS ',
    source: 'https://github.com/GABE400/gravity-media',
    visit: 'https://media-company.netlify.app/',
  },
  {
    id: 3,
    image: 'img/4.jpg',
    icon: <FaJava />,
    title: 'Java',
    category: 'Fullstack',
    tags: ['Mongo', ' Express', ' Node', ' React'],
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
    source: '#',
    visit: '#',
  },
  {
    id: 4,
    image: 'img/4.jpg',
    icon: <SiWeb3Dotjs />,
    title: 'Web 3.0',
    category: 'Decentralized',
    tags: ['Mongo', ' Express', ' Node', ' React'],
    desc: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
    source: '#',
    visit: '#',
  },
  {
    id: 5,
    image: 'img/2.png',
    icon: <FaReact />,
    title: 'React.js',
    category: 'Frontend',
    tags: ['React.js', ' ,HTML', ' ,React Styled Components'],
    desc: 'This project is a tech company website app. It was built with React, HTML and React-styled Components ',
    source: 'https://github.com/GABE400/tech-company.git',
    visit: 'https://itcompanytech.netlify.app/',
  },
  {
    id: 6,
    image: 'img/6.png',
    icon: <FaReact />,
    title: 'React.js',
    category: 'Frontend',
    tags: ['React.js', ' ,Framer Motion', ' ,HTML', ' ,Tailwind CSS'],
    desc: 'This project is a tech company website. The frontend was built using tailwind CSS and html.',
    source: 'https://github.com/GABE400/neld-tech',
    visit: 'https://neldtechnology.netlify.app/',
  },
  {
    id: 7,
    image: 'img/13.png',
    icon: <FaReact />,
    title: 'Next.js 13',
    category: 'Frontend',
    tags: ['Next.js 13', ' ,Framer Motion', ' ,HTML', ' ,Tailwind CSS'],
    desc: 'Metaverse frontend web app built using Next.js 13',
    source: 'https://github.com/GABE400/metaversus',
    visit: 'https://metaversus-gold.vercel.app/',
  },
];

export default data;
